### ISSUE TITLE
Where shoud be cakephp folder?

### ISSUE THREAD

**Issue by zhkuskov** [infinitas/infinitas#81]
Where should be cakephp folder?
In app/CakeHp?

**Comment by dogmatic69** [comment]
Cake is included as a submodule, if you use git just follow the instructions found here http://infinitas-cms.org/infinitas_docs/Installer/obtaining-infinitas

You can also have cake in another place and use php.ini to make it load (include_path config http://www.php.net/manual/en/ini.core.php#ini.include-path)
